___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid"
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [10]:

import numpy as np


### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [11]:
my_list = [5, 10, 15, 20, 25] 

np.array(my_list)


array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros.

In [12]:
array_zeros = np.zeros((5,5))
print(array_zeros)



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 4. Generate an array of 4x4 with ones and assign data type as int.

In [13]:
array_ones = np.ones((4,4), dtype = int)
display(array_ones)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [14]:
array_ones[:] = 7
display(array_ones)



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [15]:
np.full((4,4),7)



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive).

In [16]:
np.arange(2,17,2)



array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [17]:
np.arange(0,25).reshape(5,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [18]:
matrix = np.linspace(0,24,25).reshape(5,5).astype(int)
display(matrix)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [19]:

np.random.rand(5)


array([0.90917317, 0.57995395, 0.85958333, 0.99944877, 0.76338456])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [20]:
np.random.randn(5,5)



array([[ 1.32831643,  1.41455345,  0.78081867, -0.03806753, -1.48499949],
       [ 0.59942176,  0.31161281, -0.77009001, -0.71299316,  0.90211481],
       [ 1.37508587,  0.53043989,  1.26306041, -0.90906592, -0.18240664],
       [ 1.072796  , -0.91852347,  1.10266929, -0.18438282,  0.27958384],
       [-1.0938429 , -0.70479238, -0.01199564, -1.82690377,  0.22673311]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [21]:
np.random.randint(20, 50, size=(3, 4))



array([[30, 20, 49, 27],
       [35, 43, 23, 24],
       [39, 26, 39, 29]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [22]:
ranarr = np.random.rand(48)
ranarr = ranarr.reshape(6,8)
display(ranarr)



array([[0.16631735, 0.86690112, 0.91931844, 0.18388928, 0.9422553 ,
        0.43869208, 0.55049598, 0.04394472],
       [0.6008016 , 0.71427278, 0.75392061, 0.05632805, 0.00600441,
        0.23396636, 0.69396441, 0.71310822],
       [0.74041098, 0.19499512, 0.50618221, 0.54636111, 0.15984994,
        0.46195946, 0.35121366, 0.65116902],
       [0.53923359, 0.57852902, 0.57144987, 0.90645313, 0.40322343,
        0.15772585, 0.88559225, 0.9422278 ],
       [0.79719742, 0.6456245 , 0.51181906, 0.33762882, 0.87460688,
        0.04235821, 0.82790352, 0.02244647],
       [0.08283532, 0.66670272, 0.55962085, 0.01244562, 0.31759284,
        0.53025005, 0.78441729, 0.07963606]])

In [23]:
ranarr = np.random.rand(48).reshape(6,8)

display(ranarr)



array([[0.61863452, 0.28170944, 0.61454485, 0.25443589, 0.36144685,
        0.24482903, 0.39054239, 0.61147405],
       [0.85207253, 0.60922864, 0.67395177, 0.77624786, 0.76652058,
        0.05419603, 0.08362011, 0.63427966],
       [0.27848739, 0.68634399, 0.25261151, 0.23209524, 0.63126305,
        0.18668008, 0.9957788 , 0.08227879],
       [0.02101167, 0.47003432, 0.65458529, 0.69275671, 0.72183627,
        0.82576253, 0.91781844, 0.41400495],
       [0.67889727, 0.68358245, 0.27038415, 0.06781863, 0.67222969,
        0.63567327, 0.07219093, 0.09816204],
       [0.05395721, 0.26957189, 0.75948146, 0.52642248, 0.32498548,
        0.04379518, 0.56970563, 0.12817742]])

In [24]:
ranarr = np.random.randint(1, 100, 48).reshape(6, 8)
print(ranarr)



[[ 4 41 98 72 53  4 26 39]
 [92 53 97 38  4 87  3 97]
 [59 47 32 89 91 40 83 50]
 [89 78 57 33 51 78 85 40]
 [80 49 56 24 54  8 56 83]
 [78 66 45 70 90 83 23 49]]


In [25]:

ranarr = np.random.randint(0, 100, 48)
np.reshape(ranarr, (6, 8))

array([[66, 13, 65, 44, 31, 10,  7, 69],
       [77, 30, 50, 43, 30, 51, 72, 40],
       [92, 42, 37, 55, 63, 23, 33, 64],
       [63, 93, 38, 40, 47, 91,  1, 82],
       [11, 21, 88, 17, 68, 22,  3, 44],
       [97, 56, 77, 96, 13, 32, 98, 52]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [26]:
mat = np.arange(1,17).reshape(4,4)
display(mat)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [27]:
desired_output = mat[1:3, 1:3]
print(desired_output)


[[ 6  7]
 [10 11]]


### 15. Get the 1st column (index number 0) of the array above.

In [28]:
mat[:, 0]


array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [29]:
mat[1, ::2]


array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [30]:
mat[:, 2] = 77

print(mat)


[[ 1  2 77  4]
 [ 5  6 77  8]
 [ 9 10 77 12]
 [13 14 77 16]]


### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [31]:
np.array([mat[1, 0], mat[3, 2]])


array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [32]:
mat[1::2, 0::2]


array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [33]:
# LET US REMEMBER OUR ARRAY OF "mat"

print(mat)



[[ 1  2 77  4]
 [ 5  6 77  8]
 [ 9 10 77 12]
 [13 14 77 16]]


In [34]:
 mat[mat < 10]


array([1, 2, 4, 5, 6, 8, 9])

In [35]:
mat[mat > 12]



array([77, 77, 77, 13, 14, 77, 16])

In [36]:
values_smaller_than_10 = mat[mat < 10]
values_bigger_than_12 = mat[mat > 12]

(values_smaller_than_10) + (values_bigger_than_12)


array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [37]:
np.std((values_smaller_than_10) + (values_bigger_than_12))




29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [38]:
# LET US REMEMBER OUR ARRAY OF "mat"

mat



array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [39]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat"

mat = np.arange(1,17).reshape(4,4)
display(mat)




array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
# YOUR CODE IS HERE
mat[3,3]*2


32

### 23. Get the median, mean and std of 3rd column in "mat".

In [41]:
# LET US REMEMBER OUR ARRAY OF "mat"

mat



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [42]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE

mat[:, 2].reshape(-1,1)



array([[ 3],
       [ 7],
       [11],
       [15]])

In [43]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW?

mat[2, :]



array([ 9, 10, 11, 12])

In [44]:
# LET US GET MEDIAN VALUE

np.median(mat[:, 2])

9.0

In [45]:
np.median(mat[2, :])

10.5

In [46]:
# LET US GET MEAN VALUE

np.mean(mat[:, 2])



9.0

In [47]:
np.mean(mat[2, :])

10.5

In [48]:
# LET US GET STANDART DEVIATION (std) VALUE

np.std(mat[:, 2])



4.47213595499958

In [49]:
np.std(mat[2, :])

1.118033988749895

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [50]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

[pandas.read_csv() function --> (pandas official document)](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

In [51]:
!pip install py7zr

import py7zr
with py7zr.SevenZipFile('Salaries.7z', mode='r') as z:
    z.extractall()

In [52]:
# LET US READ Salaries.csv

df = pd.read_csv('Salaries.csv')

print(df)



            Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148

In [53]:
# LET US LOOK AT THE FIRST 5 ROWS

df.head()



Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [54]:
# LET US GET A SAMPLE

df.sample()



Id   EmployeeName        JobTitle   BasePay  OvertimePay  OtherPay  \
81551  81552  Robert S Rood  Deputy Sheriff  95126.51     11066.47   8862.97   

       Benefits   TotalPay  TotalPayBenefits  Year  Notes         Agency  \
81551  33413.25  115055.95          148469.2  2013    NaN  San Francisco   

       Status  
81551     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [55]:
df.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [56]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS

df.describe()



Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [57]:
# YOUR CODE IS HERE
df["Year"].value_counts()


Year
2014    38123
2013    37606
2012    36766
2011    36159
Name: count, dtype: int64

In [58]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

df["Year"].nunique()



4

In [59]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

df["Year"].unique()



array([2011, 2012, 2013, 2014], dtype=int64)

### Print out max and avg values in the column of "Totalpay".

In [60]:
# LET US FIND THE MAXIMUM TOTALPAY
df.head()



Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [61]:
df["TotalPay"].max()

567595.43

In [62]:
# LET US FIND THE AVERAGE TOTALPAY

df["TotalPay"].mean()



74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [63]:
df[df["TotalPay"] > (df["TotalPay"].mean())]




Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [64]:
df[df["TotalPay"] > (df["TotalPay"].mean())].shape[0]



69489

### How much does ALBERT PARDINI make money (including benefits)?

In [65]:
 df.loc[df["EmployeeName"] == "ALBERT PARDINI", "TotalPay"]



2    335279.91
Name: TotalPay, dtype: float64

### Who is the lowest paid person?

In [66]:


result = pd.Series(df.loc[df['TotalPay'].idxmin(), 'EmployeeName'], index=[df['TotalPay'].idxmin()])

result.name = 'EmployeeName'  

print(result)





148653    Joe Lopez
Name: EmployeeName, dtype: object


### What are the unique Jobs in dataset?

In [67]:
# YOUR CODE IS HERE
df['JobTitle'].unique()


array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [68]:
df['JobTitle'].value_counts().nsmallest(3)



JobTitle
BOARD SECRETARY - MUNICIPAL TRANSPORTATION AGENC    1
FEASIBILITY ANALYST, PORT                           1
ELECTROENCEPHALOGRAPH TECHNICIAN I                  1
Name: count, dtype: int64

### How many people earned more than avg in 2012?

### How many people have a title of Manager in their jobs?

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [71]:
# YOUR CODE IS HERE
sal_new = df.iloc[:, [0, 1, 2, 7, 8]]
print(sal_new.head())


   Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

    TotalPay  TotalPayBenefits  
0  567595.43         567595.43  
1  538909.28         538909.28  
2  335279.91         335279.91  
3  332343.61         332343.61  
4  326373.19         326373.19  


Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [72]:
# YOUR CODE IS HERE

sal_new = df.loc[:, 'EmployeeName':'TotalPayBenefits']
print(sal_new.head())

        EmployeeName                                        JobTitle  \
0     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43  
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28  
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91  
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61  
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19  


Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [76]:
# YOUR CODE IS HERE
avg_pay = df['TotalPay'].mean()
min_pay = df['TotalPay'].min()
filtered_employees = df[(df['TotalPay'] > min_pay) & (df['TotalPay'] < avg_pay)]
employee_names = filtered_employees['EmployeeName']

print(employee_names)


15847     TATYANA ROTENBERG
15848           WINSTON HOM
15849          CRAIG RIGLER
15850             WENDY TAN
15851        KENNETH BREWER
                ...        
148648          Leon Walker
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
Name: EmployeeName, Length: 79164, dtype: object


Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid"
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________